# Authors: 
         Rutvik Pansare       
         Praksha maheshwari
         Vishal Phaugat

In [ ]:
# import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mysql.connector

# connection with database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="rutu12345",
  database="project"
)
# Query to extract data from the database
query = "SELECT * FROM project.crime_data;"
df = pd.read_sql(query,mydb)

mydb.close() #close the connection


df.head()

# convert date string to datetime format
from datetime import datetime
year_query = df.copy()
dates =[]
year_query['CMPLNT_FR_DT'] = pd.to_datetime(year_query['CMPLNT_FR_DT'])
year_query['YEAR'] = pd. DatetimeIndex(year_query['CMPLNT_FR_DT']).year

In [4]:
clean = pd.read_csv("clean.csv")

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = clean
dfle.SUSP_AGE_GROUP = le.fit_transform(dfle.SUSP_AGE_GROUP)
dfle

dfle.head()
df = dfle[:200000] 

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df.drop('SUSP_AGE_GROUP',axis=1))

scaled_features = scaler.transform(df.drop('SUSP_AGE_GROUP',axis=1))
# splitting the data into test data and training data.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_features,df['SUSP_AGE_GROUP'],test_size=0.30)

#building the K-nearest neighbor model.
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix
#Printing the confusion matrix
print(confusion_matrix(y_test,pred))
print


[[ 2824  6432  2083   166   753]
 [ 6587 16993  6027   535  1634]
 [ 2130  5940  2494   244   624]
 [  133   514   219    15    43]
 [  791  1648   584    34   553]]


In [11]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.23      0.23      0.23     12258
           1       0.54      0.53      0.54     31776
           2       0.22      0.22      0.22     11432
           3       0.02      0.02      0.02       924
           4       0.15      0.15      0.15      3610

    accuracy                           0.38     60000
   macro avg       0.23      0.23      0.23     60000
weighted avg       0.38      0.38      0.38     60000

